export const apiKey = 'AIzaSyDVZm0B-6K4TlVbTPKX75dXBHZgLoWqfPs'
export const authDomain = 'pedidos-web-a7288.firebaseapp.com'
export const databaseURL = 'https://pedidos-web-a7288.firebaseio.com'
export const projectId = 'pedidos-web-a7288'
export const storageBucket = 'pedidos-web-a7288.appspot.com'
export const messagingSenderId = '473217494434'
